### ISSUE TITLE
doesn't work with angular2 rc4

### ISSUE THREAD

**Issue by Avareto** [brtnshrdr/angular2-image-zoom#1]
Hi Nick!

great work! 
That was exactly what I was looking for but It looks like there is an issue with angular2 rc4? It would be great if you could provide a simple sample or demo with your code, just to validate the directive use and comatibility with other framework versions.
Thanks!
Andreas

**Comment by xavierclotet** [comment]
Yes, i'd like to use this image zoom but maybe is not finished yet. When this will be available?

2. Allow window to be placed anywhere
3. Show viewing lens over image to show zoom area

Thx!

**Comment by brtnshrdr** [comment]
Those features are actually already implemented, I just haven't updated the TODO section of the README

**Comment by brtnshrdr** [comment]
@Avareto Sorry, I didn't see your comment before. What issues exactly are you having?

**Comment by Avareto** [comment]
angular2.rc4 requires the forms package 2.0! Your package still references the v1.0. The issue pops up when you try to install your package with an angular2.rc4 app. Try this with angular cli installed (npm install -g angular-cli):
ng new image-zoom
cd image-zoom 
npm install angular2-image-zoom --save  !! this already stops with an error.

**Comment by brtnshrdr** [comment]
I've updated the @angular/core package to rc4 and remove the other @angular packages that weren't needed. Can you let me know if that fixes your problems? (It's now version 0.5.0)

**Comment by Avareto** [comment]
unfortunately not..still getting the same error...?

**Comment by brtnshrdr** [comment]
Are you able to upload a screenshot of the error you're getting? I seem to be able to use it alongside rc4 fine. I'm also not using any of the @angular/forms stuff (old or new)

**Comment by Avareto** [comment]
![error](https://cloud.githubusercontent.com/assets/4642052/17004153/f62f6ad8-4ed3-11e6-8d07-9c7804a51043.PNG)

**Comment by Avareto** [comment]
[npm-debug.log.txt](https://github.com/brtnshrdr/angular2-image-zoom/files/374737/npm-debug.log.txt)

**Comment by brtnshrdr** [comment]
Sorry. I missed updating the "devDependencies" section in the package.json. It's fixed and published as "0.5.1". You should be good to go now!

**Comment by Avareto** [comment]
nope...still the same issue.
ng new image-zoom
cd image-zoom 
npm install angular2-image-zoom --save !!!! error

**Comment by brtnshrdr** [comment]
What version of angular-cli are you using?

**Comment by Avareto** [comment]
angular-cli: 1.0.0-beta.9
node: 4.4.7
os: win32 x64

**Comment by brtnshrdr** [comment]
Can you post your package.json file as well?

**Comment by Avareto** [comment]
{
  "name": "image-zoom",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "start": "ng serve",
    "postinstall": "typings install",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "2.0.0-rc.3",
    "@angular/compiler": "2.0.0-rc.3",
    "@angular/core": "2.0.0-rc.3",
    "@angular/forms": "0.2.0",
    "@angular/http": "2.0.0-rc.3",
    "@angular/platform-browser": "2.0.0-rc.3",
    "@angular/platform-browser-dynamic": "2.0.0-rc.3",
    "@angular/router": "3.0.0-alpha.8",
    "es6-shim": "0.35.1",
    "reflect-metadata": "0.1.3",
    "rxjs": "5.0.0-beta.6",
    "systemjs": "0.19.26",
    "zone.js": "0.6.12"
  },
  "devDependencies": {
    "angular-cli": "1.0.0-beta.9",
    "codelyzer": "0.0.20",
    "ember-cli-inject-live-reload": "1.4.0",
    "jasmine-core": "2.4.1",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "0.13.22",
    "karma-chrome-launcher": "0.2.3",
    "karma-jasmine": "0.3.8",
    "protractor": "3.3.0",
    "ts-node": "0.5.5",
    "tslint": "3.11.0",
    "typescript": "1.8.10",
    "typings": "0.8.1"
  }
}

**Comment by Avareto** [comment]
Looks like that cli is still on rc.3

**Comment by Avareto** [comment]
That was my problem, sorry.

1. I simply replaced rc.3 with .rc4
2. npm install
3. npm install angular2-image-zoom --save

and it installs with any errors.

THANKS for you great support !!!

**Comment by brtnshrdr** [comment]
Well glad it works now!

**Comment by brtnshrdr** [comment]
I've upgraded the package to be RC.6 compatible btw!
