### ISSUE TITLE
Can't bind to 'imageZoom' since it isn't a known property of 'img'

### ISSUE THREAD

**Issue by MickL** [brtnshrdr/angular2-image-zoom#6]
Added "ImageZoomModule" to imports as described in readme. Error:

`Can't bind to 'imageZoom' since it isn't a known property of 'img'`

Using latest Angular-CLI (beta 31) with Angular 2.4.x

**Comment by MickL** [comment]
Probably npm version is not correct. I don't see any decorators like `@Directive` or `@Component`.

**Comment by brtnshrdr** [comment]
Don't install it from github. Just install from NPM

'npm install angular2-image-zoom'
Then import
'import {ImageZoomModule} from 'angular2-image-zoom' 

GitHub doesn't have the correct files

**Comment by MickL** [comment]
The first comment was about `npm install angular2-image-zoom`

**Comment by brtnshrdr** [comment]
Decorators won't exist in the compiled files. I'm using this project with angular 2.4.7 just fine.

**Comment by MickL** [comment]
Still didn't work for me. I ended up using a plain JS-libary instead because this projects triggers change detection too often. Using the directive on base64 image leads to massive lags.
