### ISSUE TITLE
Customize style and position

### ISSUE THREAD

**Issue by celsomtrindade** [brtnshrdr/angular2-image-zoom#8]
I'd like to know if there is a way to customize the lens style and position.

The way I have my layout, the lens box is outside of the page. Also, I want to change border width, color, etc.. I'd like to be able to customize this.

Is it possible?

I tried applying direct style to the element, but it's not working.

**Comment by brtnshrdr** [comment]
You would probably need to user `/deep/ your-select { }`
As far as lens position, use `windowPosition` with options 1-16 to move the window
